[pytest]
log_cli = true
log_cli_level = INFO
addopts = --cov=perseus_client --cov-report=term-missing
filterwarnings =
    ignore:coroutine 'FalkorDBService.save_to_falkordb_async' was never awaited:RuntimeWarning
    ignore:coroutine 'Neo4jService.save_to_neo4j_async' was never awaited:RuntimeWarning

[coverage:run]
source = perseus_client
